return {
	permission = require("./permission"),
	message = require("./message"),
	interaction = require("./interaction"),
	guild = require("./guild"),
	embed = require("./embed"),
	channel = require("./channel"),
	application = require("./application"),
	apiTypes = require("./apiTypes"),
	voice = {},
	rest = {
		types = require("./restTypes"),
	},
	gateway = {
		types = require("./gatewayTypes"),
	},
}